# Generated by Django 2.2.2 on 2019-12-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sidebar_is_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='view_mode',
            field=models.IntegerField(default=1),
        ),
    ]
