# Generated by Django 2.2.2 on 2019-12-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191210_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='sidebar_is_on',
            new_name='is_sidebar_on',
        ),
    ]
