# Generated by Django 2.2.2 on 2019-12-05 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='(No title)')),
                ('description', models.TextField(default='')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('importance', models.IntegerField(default=0)),
                ('color', models.CharField(default='#7587C7', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
